<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */

declare(strict_types=1);

return [
    /**
     * Base namespace for DB classes
     * Used by OrmMakeDbClassesCommand command
     */
    'classes_namespace' => 'App\\Db',

    /**
     * Classes to use as parents for classes generated by OrmMakeDbClassesCommand command
     */
    'base_table_class' => \PeskyORM\ORM\Table\Table::class,
    'base_record_class' => \PeskyORM\ORM\Record\Record::class,
    'base_table_structure_class' => \PeskyORM\ORM\TableStructure\TableStructure::class,

    /**
     * DB classes builder class used to generate DB classes by table name
     * Used by OrmMakeDbClassesCommand command
     */
    'class_builder' => \PeskyORM\ORM\ClassBuilder\ClassBuilder::class,

    /**
     * Columns factory class for automatic columns creation for TableStructure
     * and for DB classes builder.
     * @see \PeskyORM\ORM\TableStructure\TableStructure::importMissingColumnsConfigsFromDbTableDescription()
     * @see \PeskyORM\ORM\ClassBuilder\ClassBuilder
     */
    'column_factory' => \PeskyORM\ORM\TableStructure\TableColumnFactory::class,

    /**
     * Traits with DB table columns declarations to use instead of declaring that columns
     * Used by OrmMakeDbClassesCommand command (passed to class_builder during table structure class generation)
     * @see TableColumnFactoryInterface::mapTypeToColumnClass()
     * @see TableColumnFactory
     */
    'type_to_column' => [

    ],

    /**
     * @see TableColumnFactoryInterface::mapNameToColumnClass()
     * @see TableColumnFactory
     */
    'name_to_column' => [
        'id' => \PeskyORM\ORM\TableStructure\TableColumn\Column\IdColumn::class,
        'created_at' => \PeskyORM\ORM\TableStructure\TableColumn\Column\CreatedAtColumn::class,
        'updated_at' => \PeskyORM\ORM\TableStructure\TableColumn\Column\UpdatedAtColumn::class,
        'password' => \PeskyORM\ORM\TableStructure\TableColumn\Column\PasswordColumn::class,
        'is_active' => \PeskyORMColumns\TableColumn\IsActiveColumn::class,
        'is_published' => \PeskyORMColumns\TableColumn\IsPublishedColumn::class,
        'is_deleted' => \PeskyORMColumns\TableColumn\IsDeletedColumn::class,
        'deleted_at' => \PeskyORMColumns\TableColumn\DeletedAtColumn::class,
        'files_metadata' => \PeskyORMColumns\TableColumn\FilesMetadataColumn::class,
        'position' => \PeskyORMColumns\TableColumn\RecordPositionColumn::class,
        'remember_token' => \PeskyORMColumns\TableColumn\RememberToken::class,
    ],

    /**
     * Class that wraps PDO instance in order to modify something or collect some data
     * By default there are 2 options:
     * 1. \PeskyORMLaravel\Profiling\PeskyOrmDebugBarPdoTracer::class - used to provide data for DebugBar library
     * 2. \PeskyORM\Profiling\TraceablePDO::class - native PeskyORM wrapper that collects stats about
     *    query execution and stores it into \PeskyORM\Profiling\PeskyOrmPdoProfiler
     */
    'pdo_wrapper' => null,
];
