<?php

return [

    /**
     * Directory where DB classes are stored.
     * Used by OrmMakeDbClasses command
     */
    'classes_path' => app_path('Db'),

    /**
     * Base namespace for DB classes
     * Used by OrmMakeDbClasses command
     */
    'classes_namespace' => '\\App\\Db\\',

    /**
     * Classes to use as parents for classes generated by OrmMakeDbClasses command
     */
    'base_table_class' => \PeskyORM\ORM\Table::class,
    'base_record_class' => \PeskyORM\ORM\Record::class,
    'base_table_structure_class' => \PeskyORM\ORM\TableStructure::class,

    /**
     * DB classes builder class used to generate DB classes by table name
     * Used by OrmMakeDbClasses command
     */
    'class_builder' => \PeskyORM\ORM\ClassBuilder::class,

    /**
     * Traits with DB table columns declarations to use instead of declaring that columns
     * Used by OrmMakeDbClasses command (passed to class_builder during table structure class generation)
     */
    'table_structure_traits' => [
        \PeskyORMLaravel\TableStructureTraits\IdColumn::class,              // id
        \PeskyORMLaravel\TableStructureTraits\IsActiveColumn::class,        // is_active
        \PeskyORMLaravel\TableStructureTraits\IsPublishedColumn::class,     // is_published
        \PeskyORMLaravel\TableStructureTraits\UserAuthColumns::class,       // password and remember_token
        \PeskyORMLaravel\TableStructureTraits\PasswordColumn::class,        // password
        \PeskyORMLaravel\TableStructureTraits\TimestampColumns::class,      // created_at and updated_at
        \PeskyORMLaravel\TableStructureTraits\CreatedAtColumn::class,       // created_at
    ]

];